### ISSUE TITLE
Could not find any documentation on using the library

### ISSUE THREAD

**Issue by ibru** [nextcloud/NextcloudKit#40]
Hello, hope you dont mind I'm contacting you this way.

I'm about to start a new iOS project which should manage files stored on NextCloud server.
I'm experimenting with NextcloudKit but I've not found any development resources so I have no idea how to sign in to cloud server, fetch list of folders/files, upload file etc.

Could you please point me to some documentation where I'd found out how to use NextcloudKit?

**Comment by mpivchev** [comment]
Hey @ibru , sorry for the delayed response, I was on vacation. 
We don't have a documentation for now, but I've recently made some integrated tests that show how to set up a local docker server, log in, and start calling functions. Please check here: https://github.com/nextcloud/NextcloudKit#testing
